### ISSUE TITLE
Recording: 2 calls to setupTrack() on first track created

### ISSUE THREAD

**Issue by shampson** [nharlow89/ShortSounds#24]
To Check: Record a sound & look at logs
    My logs show that: 
    1) Track Player 1 is initialized (setupTrack();) Attached track #587 to reverb & eq
    2) Track Player 2 is initialized (setupTrack();) Attached track #592 to reverb & eq

Conclusion: 
On stop recording for some reason creates two track players that both attach effects --> This could be leading to problems.

Possible Trace: 
Start at ModelControl::onRecordStop()

**Comment by Sigotron** [comment]
This bug was related to bug #32. When a track on a new short sound was being created, in the endRecording method, a track player was being added by both the constructor of audioplayer and in the addTrack method in audioplayer. This was the fix in the end recording method, the if clause:

if (!isNewShortSound) mAudioPlayer.addTrack(newTrack);
